title: TARDIS
baseURL: https://tardis-sn.github.io/preview/ # Remove "preview/" when ready to publish publicly
params:
  base_font: nunito-sans
  palette: blue
  favicon: images/tardis_logo.ico
  header:
    logo_img: images/tardis-logo-2.svg
    logo_img_alt: Logo
    has_nav: true
    nav_links:
      - label: Home
        url: /
        style: link
      - label: Documentation
        url: /documentation
        style: dropdown
        sub_items:
          - label: TARDIS
            url: https://github.com/tardis-sn/tardis
            style: redirect-link
          - label: Carsus
            url: https://github.com/tardis-sn/carsus
            style: redirect-link
      - label: Team
        url: /team
        style: dropdown
        sub_items:
          - label: Community Roles
            url: /team/community_roles
            style: link
          - label: Other Members
            url: /team/other_members
            style: link
          - label: Governance
            url: team/governance
            style: link
      - label: Research
        url: /research
        style: dropdown
        sub_items: 
          - label: Papers
            url: /research/papers
            style: link 
          - label: Posters
            url:  /research/posters
            style: link
      - label: Credits
        url: /credits
        style: link
      - label: News
        url: /news
        style: link #primary is another style available
  footer:
    sections:
      - type: footer_text
        image: images/tardis-banner-2.svg
        image_url: /
        image_alt: Footer logo
        # content: Stackbit theme demo
      - type: footer_nav
        title: Company
        nav_links:
          - label: About Us
            url: /about
            style: link
          - label: Blog
            url: /blog
            style: link
          - label: Sign Up
            url: /signup
            style: link
          - label: Contact
            url: /contact
            style: link
      - type: footer_nav
        title: Community
        nav_links:
          - label: Twitter
            url: "https://twitter.com/"
            style: link
            has_icon: true
            icon: twitter
            icon_position: left
          - label: LinkedIn
            url: "https://www.linkedin.com/"
            style: link
            has_icon: true
            icon: linkedin
            icon_position: left
          - label: GitHub
            url: "https://github.com/"
            style: link
            has_icon: true
            icon: github
            icon_position: left
      - type: footer_form
        title: Subscribe
        content: Stay up to date with our latest developments.
        form_id: contactForm
        hide_labels: true
        form_fields:
          - input_type: email
            name: email
            label: Email
            default_value: Enter email address
            is_required: true
        submit_label: Subscribe
    has_nav: true
    nav_links:
      - label: Terms of Service
        url: /terms-of-service
        style: link
      - label: Privacy Policy
        url: /privacy-policy
        style: link
    content: >-
      &copy; Stackbit. All rights reserved. This Jamstack site was created with
      <a href="https://www.stackbit.com/?utm_source=deployed-footer"
      target="_blank" rel="noopener">Stackbit</a>. Create yours <a
      href="https://app.stackbit.com/create?theme=azimuth&utm_source=deployed-footer"
      target="_blank" rel="noopener">now</a>.
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
      